add Targets and configurations
duckduckgo/BrowserServicesKit pull request #1069
Opened 2024-11-11 12:15 UTC by SabrinaTardio

Please review the release process for BrowserServicesKit [here](https://app.asana.com/0/1200194497630846/1200837094583426).

**Required**:

Task/Issue URL: 
iOS PR: 
macOS PR: 
What kind of version bump will this require?: Major/Minor/Patch

**Optional**:

Tech Design URL:
CC:

**Description**:

**Steps to test this PR**:
1.
1.

**OS Testing**:

* [ ] iOS 14
* [ ] iOS 15
* [ ] iOS 16
* [ ] macOS 10.15
* [ ] macOS 11
* [ ] macOS 12

---
###### Internal references:
[Software Engineering Expectations](https://app.asana.com/0/59792373528535/199064865822552)
[Technical Design Template](https://app.asana.com/0/59792373528535/184709971311943)

2024-11-13 12:01 UTC, jaceklyp requested changes

2024-11-13 12:01 UTC, jaceklyp commented on Sources/BrowserServicesKit/PrivacyConfig/AppPrivacyConfiguration.swift
> +    private func matchTargets(targets: [PrivacyConfigurationData.PrivacyFeature.Feature.Target]) -> Bool {
I'd rename to hasMatchingTarget(for

2024-11-13 13:15 UTC, SabrinaTardio commented on Sources/BrowserServicesKit/PrivacyConfig/AppPrivacyConfiguration.swift
> +        }
Yes, originally it was what Marcos and Aitor said but then actually decided it was needed so it’s gonna stay as is therefore I can remove the comment.

2024-11-15 13:58 UTC, SabrinaTardio commented
I am closing it as it is part of this one:
https://github.com/duckduckgo/BrowserServicesKit/pull/1081

2024-11-15 13:58 UTC, closed without merging